#!/usr/bin/env bash
if [ ! -f bin/kubectl ]; then
    mkdir -p bin
    wget https://storage.googleapis.com/kubernetes-release/release/v1.11.6/bin/linux/amd64/kubectl -O ./bin/kubectl
fi
rm -f function_payload.zip
rm -rf tmp
mkdir -p tmp/bin
cp -rp src/* tmp
cp -rp bin/* tmp/bin
cd tmp
pip3 install -r requirements.txt -t .
zip -r function_payload.zip *
cd ..
mv tmp/function_payload.zip .
